Exclude react-rails 2.7 from supported versions
Currently breaks server side rendering with error of the form

    ActionView::Template::Error:
    TypeError: Cannot read property 'version' of undefined

Probably related to this change:
https://github.com/reactjs/react-rails/pull/1269/files#diff-46071864dd030eabbafccec157424caade6e2c3b0f30ebaf9f4fd3f224377216R3