Migrate to supported setup-ruby action
`actions/setup-ruby` started raising error:

     ------------------------
     NOTE: This action is deprecated and is no longer maintained.
     Please, migrate to https://github.com/ruby/setup-ruby, which is being actively maintained.
     ------------------------
     Error: Version 2.6 not found